baseURL = 'https://typecombinator.github.io'
languageCode = 'en-us'
title = 'TypeCombinator Home'
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

[params]
  capitalizeTitles = false
  [params.author]
    name = "TypeCombinator"
    email = "typecombinator@foxmail.com"
    link = "https://github.com/TypeCombinator"
    avatar = "https://github.com/TypeCombinator.png"

  [params.page.code]
    maxShownLines = 1000